[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7"
tokio = { version = "1.37", features = ["full"] }

tower-http = { version = "0.5", features = ["cors"] }
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio", "macros"] }
dotenvy = "0.15"
jsonwebtoken = "9"
time = "0.3"
argon2 = "0.5"
validator = "0.16"
validator_derive = "0.16"
serde = { version = "1.0", features = ["derive"] }
